---
- name: ensure required packages are installed for Java 8
  apt: name={{item}} state=latest update_cache=yes
  with_items:
    - python-software-properties

- name: Add Java repository to sources
  action: apt_repository repo='{{apt_java_repo}}'

- name: Autoaccept license for Java
  action: shell echo {{apt_java_package}} shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

- name: Update APT package cache
  action: apt update_cache=yes

# - name: Install Java 8
#   action: apt pkg={{apt_java_package}} state=latest install_recommends=yes

# Temporary fix for webupd8team installer issue
- name: Install Oracle Java
  block:
    - apt:
        name: "{{ item }}"
        update_cache: yes
        state: latest
        force: yes
      with_items:
        - "oracle-java{{ java.version }}-installer"
        - "oracle-java{{ java.version }}-set-default"
  rescue:
    - shell: cd /var/lib/dpkg/info && sudo sed -i 's|JAVA_VERSION=8u144|JAVA_VERSION=8u152|' oracle-java8-installer.*
    - shell: cd /var/lib/dpkg/info && sudo sed -i 's|PARTNER_URL=http://download.oracle.com/otn-pub/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/|PARTNER_URL=http://download.oracle.com/otn-pub/java/jdk/8u152-b16/aa0333dd3019491ca4f6ddbe78cdb6d0/|' oracle-java8-installer.*
    - shell: cd /var/lib/dpkg/info && sudo sed -i 's|SHA256SUM_TGZ="e8a341ce566f32c3d06f6d0f0eeea9a0f434f538d22af949ae58bc86f2eeaae4"|SHA256SUM_TGZ="218b3b340c3f6d05d940b817d0270dfe0cfd657a636bad074dcabe0c111961bf"|' oracle-java8-installer.*
    - shell: cd /var/lib/dpkg/info && sudo sed -i 's|J_DIR=jdk1.8.0_144|J_DIR=jdk1.8.0_152|' oracle-java8-installer.*
  always:
    - apt:
        name: "{{ item }}"
      with_items:
        - "oracle-java{{ java.version }}-installer"
        - "oracle-java{{ java.version }}-set-default"

- name: Set Java 8 Env
  action: apt pkg={{apt_set_java_package}} state=latest install_recommends=yes

- name: check Java home
  shell: update-java-alternatives -l | awk '{ print $3 }'
  register: java_home
  ignore_errors: True
  changed_when: False

- name: set JAVA_HOME in .bashrc
  lineinfile:
    dest: '/home/ubuntu/.bashrc'
    line: 'export JAVA_HOME={{java_home.stdout}}'
    regexp: '^(# *)?export JAVA_HOME='
